"""Atomic multi-file push on the real GitHub repo."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.auth import GitHubAppAuth
from src.client import GitHubClient
from src.config import load_config

auth = GitHubAppAuth(load_config())
client = GitHubClient(auth)

files = [
    {"path": "docs/index.md", "content": "# Documentation\n\nGenerated by gh-api-cli.\n"},
    {"path": "src/utils.py", "content": 'def greet(name):\n    return f"hi {name}"\n'},
    {"path": "tests/test_smoke.py", "content": 'import sys\nsys.path.insert(0, ".")\nfrom src.utils import greet\n\n\ndef test_greet():\n    assert greet("world") == "hi world"\n'},
]

commit = client.push_files(
    "orvyx", "demo-live-action", files,
    message="feat: atomic multi-file commit (3 files in 1 commit)",
    branch="feat/api",
)
print(f"Atomic commit {commit['sha'][:10]}... ({len(files)} files in 1 commit) on feat/api")
